spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_smarthealth
    username: root
    password: 133226
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl